title: Hadi Seyedi
# logo: /assets/img/Hadi_photo2.jpeg
logo: /assets/img/Hadi_photo.png
description:                         
#show_downloads: true
theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
